# Trigger
# Stages
# - Jobs
# - - Steps
# Runners - Github hosted / self hosted


name: 'Grocery App Infra - Dev'

on:
  push:
    branches:
      - dev

jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - name: Initialize
        run: echo "Initialize"