# Trigger
# Stages
# - Jobs
# - - Steps
# Runners - Github hosted / self hosted


name: 'Grocery App Infra - Dev'

on:
  push:
    branches:
      - dev

jobs:
  plan:
    name: Plan
    environment: DEV
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure Login action
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Terraform Initialize
        run: |
          terraform init

      - name: Terraform Plan
        run: |
          terraform plan -out=plan-${{ github.run_number }}.tfplan
      
      - uses: actions/upload-artifact@v4
        with:
          name: artifact
          path: plan-${{ github.run_number }}.tfplan